"""Public imports for the Appendix C core companion examples."""

from .architecture import (
    FixedClock,
    InMemoryExecutionAdapter,
    JobApplication,
    ListOutput,
    SequenceIds,
    compose_application,
)
from .direct import run, shipping_cost_direct, transfer_decision
from .domain import (
    DecisionRecord,
    ExecutionBoundaryError,
    InvalidDecisionRecord,
    InvalidJob,
    Job,
    PatternError,
    Result,
    UnknownSelection,
)
from .essential import (
    DirectExecutor,
    LegacyRunnerAdapter,
    LegacyRunnerError,
    LegacyRunnerFake,
    PolicyExecutor,
    build_executor,
    express_shipping,
    keep_payload,
    run_with_policy,
    select_policy,
    shipping_cost_with_policy,
    standard_shipping,
    uppercase_payload,
)
from .professional import (
    JobEventSubject,
    MeasuringExecutor,
    NotificationReport,
    ObserverFailure,
    ObserverLimitError,
    Subscription,
)


__all__ = [
    "DecisionRecord",
    "DirectExecutor",
    "ExecutionBoundaryError",
    "FixedClock",
    "InMemoryExecutionAdapter",
    "InvalidDecisionRecord",
    "InvalidJob",
    "Job",
    "JobApplication",
    "JobEventSubject",
    "LegacyRunnerAdapter",
    "LegacyRunnerError",
    "LegacyRunnerFake",
    "ListOutput",
    "MeasuringExecutor",
    "NotificationReport",
    "ObserverFailure",
    "ObserverLimitError",
    "PatternError",
    "PolicyExecutor",
    "Result",
    "SequenceIds",
    "Subscription",
    "UnknownSelection",
    "build_executor",
    "compose_application",
    "express_shipping",
    "keep_payload",
    "run",
    "run_with_policy",
    "select_policy",
    "shipping_cost_direct",
    "shipping_cost_with_policy",
    "standard_shipping",
    "transfer_decision",
    "uppercase_payload",
]
