from __future__ import annotations

from collections.abc import Callable, Iterable
from enum import Enum
from typing import Any

class FaststatsError(RuntimeError): ...

class Summary:
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    @property
    def count(self) -> int: ...
    @property
    def minimum(self) -> float: ...
    @property
    def maximum(self) -> float: ...
    @property
    def mean(self) -> float: ...
    @property
    def anomaly_count(self) -> int: ...
    @property
    def anomaly_ratio(self) -> float: ...

class ProcessingMode(Enum):
    COPIED = ...
    BORROWED = ...

def summarize(samples: Iterable[int | float], *, threshold: int | float = ...) -> Summary: ...
def summarize_many(samples: Iterable[int | float], *, threshold: int | float = ...) -> Summary: ...
def summarize_buffer(buffer: object, *, threshold: int | float = ...) -> Summary: ...
def normalize_in_place(buffer: object) -> None: ...
def summarize_with_progress(
    samples: Iterable[int | float],
    *,
    threshold: int | float = ...,
    callback: Callable[[int, float], object],
) -> Summary: ...

class OnlineStats:
    def __init__(self) -> None: ...
    def add(self, value: int | float) -> None: ...
    def extend(self, values: Iterable[int | float]) -> None: ...
    def reset(self) -> None: ...
    @property
    def count(self) -> int: ...
    @property
    def minimum(self) -> float | None: ...
    @property
    def maximum(self) -> float | None: ...
    @property
    def mean(self) -> float | None: ...

class Metadata:
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    @property
    def label(self) -> str: ...

class Dataset:
    def __init__(self, label: str) -> None: ...
    @property
    def metadata(self) -> Metadata: ...

class BorrowingView:
    def __init__(self, dataset: Dataset) -> None: ...
    @property
    def label(self) -> str: ...

class TrackedResource:
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    @property
    def name(self) -> str: ...
    @staticmethod
    def live_count() -> int: ...

def make_resource(name: str) -> TrackedResource: ...
def consume_resource(resource: TrackedResource) -> None: ...

class ProgressObserver:
    def __init__(self) -> None: ...
    def on_progress(self, completed: int) -> None: ...

class ObserverRunner:
    def __init__(self, observer: ProgressObserver) -> None: ...
    def run(self, completed: int) -> None: ...

def _raise_domain_error_for_test() -> None: ...
