from collections.abc import Iterable
from typing import final

__all__ = ["OnlineStats", "Summary", "describe_payload", "summarize"]

@final
class Summary:
    @property
    def count(self) -> int: ...
    @property
    def minimum(self) -> float: ...
    @property
    def maximum(self) -> float: ...
    @property
    def mean(self) -> float: ...
    @property
    def anomaly_count(self) -> int: ...
    @property
    def anomaly_ratio(self) -> float: ...

@final
class OnlineStats:
    def __init__(self) -> None: ...
    @property
    def count(self) -> int: ...
    @property
    def minimum(self) -> float | None: ...
    @property
    def maximum(self) -> float | None: ...
    @property
    def mean(self) -> float | None: ...
    def add(self, /, value: int | float) -> None: ...
    def extend(self, /, values: Iterable[int | float]) -> None: ...
    def reset(self) -> None: ...

def summarize(samples: Iterable[int | float], *, threshold: int | float) -> Summary: ...
def describe_payload(
    label: str, payload: bytes, note: str | None = None
) -> tuple[str, int, bool]: ...
